name: quote_generator

on:
  workflow_dispatch:
  # 00:00 UTC
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: npm ci
    - name: Generate quote
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: | 
        npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "heimer.nguyen@gmail.com"
        git config --global user.name "GitHub"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
